### ISSUE TITLE
Error al subir múltiples archivos en problemas nuevos

### ISSUE THREAD

**Issue by fffeelipe** [JuezUN/INGInious#105]
Cuando se crea un nuevo problema, subir múltiples archivos da el siguiente error:

There was an error while uploading the files: 0.in, 0.out, 1.in, 1.out, 2.in, 2.out. They may be already uploaded.

Pero no hay nada subido.

**Comment by amicis31** [comment]
El problema es una configuración interna de inginious que no se ha podido solucionar, Cuando se crea la tarea no se crea un directorio hasta presionar "save", sin este directorio no existe un lugar al cual guardar los archivos.
![](https://thumbs.gfycat.com/OpulentLivelyAffenpinscher-size_restricted.gif)

**Comment by crdgonzalezca** [comment]
Did you check what happened with the added message? @amicis31 Can we close this?

**Comment by crdgonzalezca** [comment]
Indeed looks fixed.
