### ISSUE TITLE
Tasks in task lists have no order.

### ISSUE THREAD

**Issue by fffeelipe** [JuezUN/INGInious#109]
It would be usefull to have the course's tasks sorted by date, so it's easier to group them.

**Comment by fffeelipe** [comment]
Having the task ordered primarily by date, and secondly by name where the most recent is at the top would be a organized way to show the tasks.

**Comment by amicis31** [comment]
This feature could be possible, but the problem will be the internal way inginious adds this feature

**Comment by amicis31** [comment]
![](https://thumbs.gfycat.com/MildPlayfulIcelandgull-size_restricted.gif)
