### ISSUE TITLE
Bug with custom input - showing a weird exception

### ISSUE THREAD

**Issue by NicolasRestrepoTorres** [JuezUN/INGInious#150]
Sometimes when trying to submit code with _custom input_ in Python, there is an unexpected issue (see image to take a look at the example)

`Exception ignored in: <bound method Socket._del_ of <zmq.sugar.socket.Socket object at 0x7fbce37d1d48>>
Traceback (most recent call last):
  File "/usr/lib64/python3.5/site-packages/zmq/sugar/socket.py", line 67, in _del_
  File "/usr/lib64/python3.5/site-packages/zmq/sugar/socket.py", line 105, in close
  File "/usr/lib64/python3.5/site-packages/zmq/sugar/context.py", line 153, in _rm_socket`

![Issue Python](https://user-images.githubusercontent.com/22863602/76135414-c29dc580-5ff4-11ea-8b6c-9f35abd1f345.jpeg)

**Comment by crdgonzalezca** [comment]
[JuezUN/INGInious-containers#25](https://github.com/JuezUN/INGInious-containers/pull/25) fixes this issue.

**Comment by crdgonzalezca** [comment]
This needs to be reopened as the fix opens a security issue that allows students to see the grading files. The problem occurs when a second container is launched from the container using `run_student` API, and the err is for all languages and it does not occur always, being a problem with the Sockets communication. 
We have to figure out another way to fix this.

**Comment by crdgonzalezca** [comment]
PR [INGInious-containers#28](https://github.com/JuezUN/INGInious-containers/pull/28) fixes temporally this issue. This is temporal because we are by now hiding this message to the student but we have not found what is causing this.
