### ISSUE TITLE
Special chars in Output diff

### ISSUE THREAD

**Issue by ferestrepoca** [JuezUN/INGInious#159]
When you use special chars in the inputs, it is possible that the "output diff" option is not showed properly to users. For example, the second wrong answer in this case:
![Captura](https://user-images.githubusercontent.com/11912846/78783036-9c0ed980-7968-11ea-81f5-98f75f2d0c48.PNG)

**Comment by NicolasRestrepoTorres** [comment]
This bug can also happen with a input not composed exclusively from special characters, as happens in ths specific problem https://uncode.unal.edu.co/course/pc-group18_2020_1/vigenere at some submissions.
![Selección_682](https://user-images.githubusercontent.com/22863602/78949821-6fef7780-7a92-11ea-871c-9f0ba2485986.jpg)
![Selección_681](https://user-images.githubusercontent.com/22863602/78949823-70880e00-7a92-11ea-89c8-5e78eec54e97.jpg)
