### ISSUE TITLE
Problem with images in RST

### ISSUE THREAD

**Issue by NicolasRestrepoTorres** [JuezUN/INGInious#161]
When describing a problem, it is shown under help that an image should be uploaded as follows:
![Selección_683](https://user-images.githubusercontent.com/22863602/78950181-8944f380-7a93-11ea-95e0-cd1cd56a82b4.jpg)
But it must be specified that the image must be under a /public/<path>/ and also it could be shown that it can work by adding the extension of the image as well.

**Comment by crdgonzalezca** [comment]
Fixed.
