### ISSUE TITLE
Submission history is not shown properly.

### ISSUE THREAD

**Issue by crdgonzalezca** [JuezUN/INGInious#26]
When you have many submissions for the same task, the submission history is too long for the template. As shown in the next image:
![bug1](https://user-images.githubusercontent.com/22863695/48439233-c6e50600-e753-11e8-839a-c94389327b7c.png)

The fix would be making shorter the Submission history.

**Comment by crdgonzalezca** [comment]
This is another example where the user only has one submission but it is almost 'invisible'. **This is happening with all kind of users**.

![image](https://user-images.githubusercontent.com/22863695/48440391-d31e9280-e756-11e8-95be-5b09d090fea3.png)

**Comment by amicis31** [comment]
One possible solution could be to restrict the movement of this sidebar. which is relatively easy

**Comment by amicis31** [comment]
Because this is an temporal solution I will keep the issue open.
