### ISSUE TITLE
Create tasks using like a template

### ISSUE THREAD

**Issue by crdgonzalezca** [JuezUN/INGInious#267]
**Is your feature request related to a problem? Please describe.**
Creating a task takes a while to correctly set it up, this is more difficult when a instructor has to create several tasks related to, for instance, the same topic.

**Describe the solution you'd like**
The instructors may create tasks using base templates which contains the basic information.

**Additional context**
This may be like creating templates from a given task, like creating images form a OS. Probably a new plugin is necessary but  this needs to be discussed.

**Comment by AndresFelipeCastellanos** [comment]
I think this issues could be closed. We talk the last week that it's not necessary to do a new plugin to manage task templates, since UNCode has the `problem bank` option to copy and manage task problems, so is not necessary to create another plugin to manage task templates yet.
