### ISSUE TITLE
Password registering for a course

### ISSUE THREAD

**Issue by crdgonzalezca** [JuezUN/INGInious#27]
When you are registering for a course, the password input field is no show as a password, it is shown as plain text. Also, this field allows 'autocomplete' so we can see previously used passwords in the same client (This could lead to a 'hacking').

![image](https://user-images.githubusercontent.com/22863695/48441852-8b9a0580-e75a-11e8-9c76-d623560dd4e6.png)

**Comment by amicis31** [comment]
The problem can be found in [/inginious/frontend/templates/mycourses.html](https://github.com/JuezUN/INGInious/blob/0a2ed07e21725b777fce15ba75a1f04e9cc12ebf/inginious/frontend/templates/mycourses.html#L121) line 121. 

This concern should be for UCL-INGI.

**Comment by crdgonzalezca** [comment]
A PR was done to INGInious team ([#429](https://github.com/UCL-INGI/INGInious/pull/429)). Already approved and master updated with this change.
