### ISSUE TITLE
Fixes on Tags handling

### ISSUE THREAD

**Issue by crdgonzalezca** [JuezUN/INGInious#325]
**Describe the bug / issue**

Looks like there are some things of task tags that are not working, specifically the counter of succeeded tags as shown in the screenshot. When you submit a task, it is always showing a 0 in the tags span of the submission history.

**Expected behavior**
I think this should show the number of tags or skills that the student accomplished.

**Screenshots**
![image](https://user-images.githubusercontent.com/22863695/117234828-56cb0e80-adeb-11eb-8b85-eb61c996cdbc.png)

**Comment by choudharymuskan** [comment]
I think I can debug this issue, so could you please show me the source code so i can work one the requirement or You can try Automating Numbering With Counters.
CSS counters are like "variables". The variable values can be incremented by CSS rules (which will track how many times the student has done submission)

YOU CAN USE THE FOLLOWING PROPERTY OF CSS COUNTER:
counter-increment - Increments a counter value.
counter() function - Adds the value of a counter to an element.

for example

Suppose you want it for h2 tag
**//Mandatory for resetting the section**
body {
  counter-reset: section;
}
**//Varies for different tags**
h2::before {
  counter-increment: section;
  content: "Section " counter(section) ": ";
}

**Comment by crdgonzalezca** [comment]
Hi @choudharymuskan, thanks for your interest and suggestions, we really appreciate it.

Although, in this case this issue refers to some internal tags that the tasks have, this to add some skills or conceptual tags to the tasks that students solve, it is not actually related to HTML tags.

If you are still interested in contributing with us, let me know and we can chat more about this issue and how this might be solve. In the meantime make sure to read our documentation https://github.com/JuezUN/INGInious/wiki, https://juezun.github.io/, https://github.com/JuezUN/INGInious, to understand more about this project and how to set the development environment up.

Thanks again.
