### ISSUE TITLE
Add documentation about HDL tasks/submissions

### ISSUE THREAD

**Issue by crdgonzalezca** [JuezUN/INGInious#351]
**Is your feature request related to a problem? Please describe.**
Right now, there is no documentation about HDL tasks, thus we do not how to create this kind of task or to generate a good grader for this.

**Describe the solution you'd like**
We need to add documentation to the wiki and add videos (add them to the web page) about how to create this type of task (for instructors) and how to submit (for students).

**Comment by ferestrepoca** [comment]
#Done
Closing this issue as @andrescorso has already completed the docs in the wiki (https://github.com/JuezUN/INGInious/wiki/How-to-create-a-task#hdl-tasks-verilogvhdl) and published some tutorial videos on how to create/submit HDL tasks (https://juezun.github.io/pages/documentation.html).
