### ISSUE TITLE
Automatically register students to UNCode from LTI pages

### ISSUE THREAD

**Issue by AndresFelipeCastellanos** [JuezUN/INGInious#360]
**Is your feature request related to a problem? Please describe.**
When students register for an LTI course on OpenEdx, they also need to register in that course on UNCode, either from a .csv file, or manually. There is no way to register students in a LTI course and automatically register them on UNCode.

**Describe the solution you'd like**
Allow to automatically register students on UNCode from a LTI course on OpenEdx using webhooks.

**Comment by AugustH** [comment]
maybe a starting point:
https://github.com/UCL-INGI/INGInious/pull/620
