### ISSUE TITLE
Some problems with whitespace characters in Notebook test cases

### ISSUE THREAD

**Issue by AndresFelipeCastellanos** [JuezUN/INGInious#386]
**Describe the bug / issue**
There are errors in notebook test cases when a student submits for some notebook problems. Some characters are ignored in the test cases files, e.g, the last whitespace character in the test cases doesn't exists in the grader, but does exists in student output.

**Expected behavior**
We need to fix these errors to allow notebook grader to properly grade the student's submissions.

This is an example of an output difference for two test cases in a notebook task

![imagen](https://user-images.githubusercontent.com/45008613/145151364-708c3df1-ad66-4956-b948-64c291342a9b.png)

**Comment by VirtualDiegox** [comment]
Now this can be closed with the fixes on PR #75 on JuezUN/INGInious-containers
