### ISSUE TITLE
Requesting plugin documentation 

### ISSUE THREAD

**Issue by ranjiGT** [JuezUN/INGInious#391]
Hello UNCode community,

I was unable to find the plugin documentation for UNCode used in the `configuration.yaml` file. If you could please add the same in the wiki pages or if documented elsewhere kindly give information on it.

**Comment by VirtualDiegox** [comment]
Thanks for your feedback, we noticed that the links to the plugins documentation page were broken, but they are now fixed.
If you have any further questions about the UNCode plugin please let us know.
