### ISSUE TITLE
Plot statistics using task id instead of task name.

### ISSUE THREAD

**Issue by crdgonzalezca** [JuezUN/INGInious#43]
For the case of **course statistics** and **user statistics**, there are two charts using the task id instead of the alert to show the graph. This is for the case of 'Submissions Verdict' (both charts) as shown in the next image (X axis), also, the user statistics uses the task id instead of the task name. This could be a problem as an ID not necessarily describes the task.

![image](https://user-images.githubusercontent.com/22863695/48514086-7345eb80-e82b-11e8-9070-50d47e8c3b91.png)

Also, the task names, when they are long, are not displayed very well as shown in the next image:
![image](https://user-images.githubusercontent.com/22863695/48514185-bc963b00-e82b-11e8-92f0-79172b05eefb.png)
The task names are in the X axis but there are some incomplete.

**Comment by ferestrepoca** [comment]
It's better to show the task name.
