### ISSUE TITLE
User Management Unable to retrieve certain users

### ISSUE THREAD

**Issue by gaperezsa** [JuezUN/INGInious#464]
**Describe the bug / issue**
In some cases, it has been observed that the User Management plugin is unable to retrieve the full information of some users and just freezes "loading" when asked for said information.

**To Reproduce**
1. open User Management plugin
2. Search for example for "heldeg"
3. click on the user retrieved by that search
4. See frozen "loading" state

**Expected behavior**

As seen with most of other users, when they are clicked, the page expands showing full information of their account. There should not be exceptions like this one. 

**Screenshots**
![image](https://user-images.githubusercontent.com/56688374/180872448-76128e7c-b6e8-400a-9177-1e94c73e73b6.png)

**Desktop:**
 - Browser Mozilla Firefox

**Comment by ferestrepoca** [comment]
I've reopened this issue because the proposed fix seems not to work.
