### ISSUE TITLE
Show differences for professors 

### ISSUE THREAD

**Issue by jreinaz** [JuezUN/INGInious#477]
**Is your feature request related to a problem? Please describe.**
Is not a problem, is more related with help professors in evaluating.

**Describe the solution you'd like**
It would be interesting when students make submissions professors can see the differences, like a "show diff" but in this case for professors instead of students.

**Describe alternatives you've considered (if applicable)**
We have considered two alternatives:
1)Modify graders logic, because the differences are calculated according to a list that indicates the container in which tests calculate differences, and also the logic required for show it only to the professor.
2)If it is not possible to show differences directly, professor would have to resend the submission so we can show all differences.

**Comment by VirtualDiegox** [comment]
Solved with #484
