### ISSUE TITLE
Logging in and loggin out may take you to an unknown page or error page.

### ISSUE THREAD

**Issue by crdgonzalezca** [JuezUN/INGInious#48]
When you log in and the URL in the browser is different from /courselist this may lead you to an unknown page, the same case when you log out. To do this, if you are for example viewing a task, then you log out and try to log in again, this will take you to an unknown page or an error as the images show.

This image shows the URL and page where you are in before logging out.
![image](https://user-images.githubusercontent.com/22863695/48516624-d2a6fa00-e831-11e8-8259-d2128706af99.png)

This is the page you get when log out.
![image](https://user-images.githubusercontent.com/22863695/48516916-bbb4d780-e832-11e8-983b-2917c9de20fb.png)

To fix this, a possible solution could be redirecting to /signin when you log out and redirecting to /courselist when you log in every time, so we avoid incorrect URLs.

**Comment by crdgonzalezca** [comment]
I was testing this in my localhost, testing now in production, looks like it is not happening.

**Comment by amicis31** [comment]
This problems still happends on production
![](https://thumbs.gfycat.com/DeadParchedChamois-size_restricted.gif)

**Comment by amicis31** [comment]
This problem can be found on:
- [inginious/frontend/pages/utils.py#L186](https://github.com/JuezUN/INGInious/blob/0589712d6562b4f6adb70b83c5ea55e05c6c8d56/inginious/frontend/pages/utils.py#L186)
- [inginious/frontend/pages/utils.py#L190](https://github.com/JuezUN/INGInious/blob/0589712d6562b4f6adb70b83c5ea55e05c6c8d56/inginious/frontend/pages/utils.py#L190)

In my opinion we should make a pull request for the UCL-INGI repository

**Comment by amicis31** [comment]
Solved on the [UCL-INGI repository](https://github.com/UCL-INGI/INGInious/pull/398)
