### ISSUE TITLE
Creating a task fails if current URL has more data like # in the end

### ISSUE THREAD

**Issue by crdgonzalezca** [JuezUN/INGInious#65]
When you save a task and then delete ti, you get the next URL.
![image](https://user-images.githubusercontent.com/22863695/49123335-3d225600-f286-11e8-9ea4-22744d8dd627.png)

After this, If you try to create a task again, the following happens:
![image](https://user-images.githubusercontent.com/22863695/49123500-c9cd1400-f286-11e8-9bd1-268a802cd127.png)

The URL is modified but it does not redirect to task edit page and the URL is wrong.

This is happening because the text **#task_edit_submit_status** is in the end of the URL so the URL is not built correctly.

**Comment by amicis31** [comment]
This problem doesn't happen anymore
