### ISSUE TITLE
Python tutor takes python3 as python2

### ISSUE THREAD

**Issue by amrondonp** [JuezUN/INGInious#72]
Python tutor virualizes python2 when python3 is selected in the dropdown

![image](https://user-images.githubusercontent.com/6508705/49595030-24303980-f945-11e8-985a-942860d9468d.png)

![image](https://user-images.githubusercontent.com/6508705/49595128-5a6db900-f945-11e8-86b0-3fbd592177d6.png)

**Comment by crdgonzalezca** [comment]
I've been looking to this issue. What I found that if code is python, we are always generating the python iframe as python 2.x, in file plugins/multilang/static/pythonTutor.js method
![image](https://user-images.githubusercontent.com/22863695/57101232-638d6700-6ce6-11e9-909e-d2f254c20eb9.png) There you will find more about that problem.

I tried to change this here to see if that fixes the problem, but it does not fix the problem. So I started to thing that is a problem in python tutor container.

Important files on the embeded python tutor are listed below:
- https://github.com/JuezUN/OnlinePythonTutor/blob/master/v3/js/iframe-embed.js
- https://github.com/JuezUN/OnlinePythonTutor/blob/master/v3/iframe-embed.html
- https://github.com/JuezUN/OnlinePythonTutor/blob/master/v3/js/pytutor.js
- https://github.com/JuezUN/OnlinePythonTutor/blob/master/v3/js/opt-frontend-common.js

To see more about how we are embed python tutor on UNCode see https://github.com/JuezUN/OnlinePythonTutor/blob/master/v3/docs/embedding-HOWTO.md

**FIX:** I think first we should fix our pythonTutor.js file in the sense to generate the correct iFrame, second, see what is going on in the container.

**Comment by crdgonzalezca** [comment]
The way it was fixed is to have two separate containers for pythontutor, one for python2 and other for python3 and the other languages. This is because as default is took py2 as default. A better fix would be a big change.

**Comment by crdgonzalezca** [comment]
Updated the Python tutor deployment services to take build and runtime arguments to build depending two separate services. One for all languages and other specific for python 2. JuezUN/Deployment#45 and JuezUN/OnlinePythonTutor#7. That way the deployment is automatic.
Also, the changes on this repo to allow these changes #129

**Comment by crdgonzalezca** [comment]
UPDATE: As Python 2 support is removed, this can be closed because only one container is deployed.
