### ISSUE TITLE
Custom input does not work

### ISSUE THREAD

**Issue by crdgonzalezca** [JuezUN/INGInious#84]
When you go to /submission/<submission_id> you can see the tools option but the custom input does not work. Looks like it doesn't even make the request.

**Comment by amicis31** [comment]
If there is not a request, you need to activate custom_input plugin.
Then the problem is that the course and task are unknown for the api

**Comment by amicis31** [comment]
One possible option is to create another API, which receives as parameter the Identifier of the submission (This information is now present on the URL), and asks for the course_id and tasks_id directly on this API.

**Comment by amicis31** [comment]
It seems that custom input also doesn't work on the task submission.
