### ISSUE TITLE
When the code is too long or time consuming, Pythontutor does not work.

### ISSUE THREAD

**Issue by crdgonzalezca** [JuezUN/INGInious#85]
When you try to use python tutor on long code submissions (for instance: https://uncode.unal.edu.co/submission/5c5858189dc6d62d79243ad7) it won't work annd it just times out and shows the next message.

![image](https://user-images.githubusercontent.com/22863695/53845593-a7c6ea00-3f77-11e9-8b48-0f2f2ef0d68f.png)

**Note:** The example code is not actually a long code, it is 89 lines only.

**Comment by amicis31** [comment]
This problem is native of PythonTutor nothing to do here, you will need to work on the original project. See [Unsupported Features](https://github.com/pgbovine/OnlinePythonTutor/blob/master/unsupported-features.md)

**Comment by crdgonzalezca** [comment]
As we already now PythonTutor does not support long code executions, we won't fix this as it might be time consuming.
