### ISSUE TITLE
Add code template feature for student

### ISSUE THREAD

**Issue by amicis31** [JuezUN/INGInious#89]
This feature is about presenting the student with a piece of code written by the teacher for its modification. This allows:
- Instead of the student writing all necessary code, the student just writes the main part for the lesson

**Comment by crdgonzalezca** [comment]
Is this fixed?

**Comment by crdgonzalezca** [comment]
Offline chat: This is provisionally fixed as the code template is specific for only one language, the next step would be to allow uploading code template for all the allowed languages for task.

**Comment by crdgonzalezca** [comment]
I think the last PR fixes in a better way this issue as professors are now able to upload several files containing the code template, and the select which file corresponds to an specific language. That way, this tool works for all available languages.
I am going to close this as I think that a definitive fix.
